### ISSUE TITLE
Price displayed as undefined

### ISSUE THREAD

**Issue by fnando** [oktapodia/coinwatch#13]
Hi,

I just tried adding Stellar (XLM) to BTC and this is what I get:

![2017-11-05 at 09 07](https://user-images.githubusercontent.com/3009/32417099-e131f19c-c208-11e7-9064-e680b7144fcf.png)

**Comment by oktapodia** [comment]
Thanks for your feedback, I'm on it

**Comment by oktapodia** [comment]
@fnando The issue is fixed on [v0.2.2](https://github.com/oktapodia/coinwatch/releases/tag/v0.2.2)

Thanks again!
